#!/bin/sh

first="$1"
second="$2"

reposition(){
	if [[ $1 == *.* ]]; then
		echo $(echo $1 | awk -F '.' '{print $3"-"$2"-"$1}')
	fi
}

first=$(reposition $first)
second=$(reposition $second)

first=$(date --date="$first" +%s)
second=$(date --date="$second" +%s)
seconds=$(($first - $second))
day=$((60*60*24))

echo $(( $seconds/ $day ))