#!/bin/sh

# Invoke with search pattern and path. Example: ./contentsearch "Test" /home/$(whoami)
# The path is optional. If no path is given . is used as path.

pattern="$1";
path="$2";

if [ -z "$path" ]; then
	path=".";
fi;

grep -rc -e "$pattern" "$path" 2> /dev/null | awk -F ":" '$2 != 0 {print $2" "$1}' | sort -n | awk '{print $2" "$1}';
