#!/bin/sh

# Invoke with search pattern and path. Example: ./contentsearch "Test" /home/$(whoami)
# The path is optional. If no path is given . is used as path.

# TODO Make it possible to find pattern in files with whitespaces within their names.

pattern=${1:-.}
path="$2";

grep -rc -e "$pattern" "$path" 2> /dev/null | awk -F ":" '$2 != 0 {print $2" "$1}' | sort -n | awk '{print $2" "$1}';
